"""Shared test fixtures, generated by the scaffold task.

`db_session` gives a test a real SQLAlchemy session. USE IT rather than building your own
engine: a test that hardcodes `create_engine("sqlite:///...")` is asserting against a
different database than the one the application deploys onto, and the two disagree about
timezone-aware columns, column lengths, integer ranges and CHECK constraints.

Where DATABASE_URL is set (the deploy container) the fixture uses that engine, so the test
verifies the real thing. Where it is not (a laptop, the build probe) it falls back to a
sqlite file under `tmp_path`.

Either way the test's work is ROLLED BACK when it finishes, so no test sees what another
left behind and running against a real database never changes that database's contents.
Do not commit expecting the row to persist beyond your test -- it will not.
"""
from __future__ import annotations

import os

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.models import Base


@pytest.fixture
def db_session(tmp_path):
    """A session on the real engine when DATABASE_URL is set, else a private sqlite file."""
    # A blank value means unconfigured -- same reasoning as db_url.py.
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        # Never the app's shared default file: a suite sharing one database reports on the
        # order it ran in, not on the application.
        url = f"sqlite:///{tmp_path / 'test.db'}"
    engine = create_engine(url)
    Base.metadata.create_all(engine)

    # Bind the session to a connection holding an open transaction, and roll that back at the
    # end. This is what isolates tests from each other on a SHARED database (the deploy's
    # Postgres), where `tmp_path` cannot help -- and what keeps a test run from writing into
    # the deployed application's data. The session's own commit()s land inside this outer
    # transaction, so the code under test behaves normally and nothing survives the test.
    connection = engine.connect()
    transaction = connection.begin()
    session = sessionmaker(bind=connection)()
    try:
        yield session
    finally:
        session.close()
        if transaction.is_active:
            transaction.rollback()
        connection.close()
        engine.dispose()
