"""Shared component contract — canonical DTOs + service interfaces.

Generated by the scaffold task. EVERY component imports its types and interfaces
from here (never redefine them) so producers and consumers agree.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, List, Optional, Protocol  # noqa: F401
from uuid import UUID  # noqa: F401

from pydantic import BaseModel

class RecipeDTO(BaseModel):
    id: int
    name: str
    ingredients: str
    created_at: datetime
    updated_at: datetime

class RecipeCreateDTO(BaseModel):
    name: str
    ingredients: str

class RecipeUpdateDTO(BaseModel):
    name: str
    ingredients: str

class RecipeNotFoundError(Exception):
    """A recipe with the given id does not exist or the id is malformed"""

class ValidationError(Exception):
    """One or more recipe fields fail validation (empty, too long, or otherwise invalid)"""

class RecipeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    id: int
    name: str
    ingredients: str
    created_at: datetime
    updated_at: datetime

class RecipeServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create(self, data: RecipeCreateDTO) -> int: ...
    def update(self, recipe_id: int, data: RecipeUpdateDTO) -> Any: ...
    def get_by_id(self, recipe_id: int) -> RecipeDTO: ...
    def list_all(self) -> list[RecipeDTO]: ...
