"""Shared component contract — canonical DTOs + service interfaces.

Generated by the scaffold task. EVERY component imports its types and interfaces
from here (never redefine them) so producers and consumers agree.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, List, Optional, Protocol  # noqa: F401
from uuid import UUID  # noqa: F401

from pydantic import BaseModel

class RecipeDTO(BaseModel):
    id: int
    name: str
    ingredients: str
    created_at: datetime
    updated_at: datetime

class ValidationError(ValueError):
    """Input validation fails for recipe name or ingredients (empty, whitespace-only, or exceeds max length)"""

class RecipeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    id: int
    name: str
    ingredients: str
    created_at: datetime
    updated_at: datetime

class RecipeServiceProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    def create_recipe(self, name: str, ingredients: str, db: Any) -> RecipeDTO: ...
    def get_recipe(self, id: int, db: Any) -> Any: ...
    def update_recipe(self, id: int, name: str, ingredients: str, db: Any) -> RecipeDTO: ...
    def list_recipes(self, db: Any) -> list[RecipeDTO]: ...
