"""Shared component contract — canonical DTOs + service interfaces.

Generated by the scaffold task. EVERY component imports its types and interfaces
from here (never redefine them) so producers and consumers agree.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, List, Optional, Protocol  # noqa: F401
from uuid import UUID  # noqa: F401

from pydantic import BaseModel

class RecipeData(BaseModel):
    id: UUID
    name: str
    ingredients: str
    created_at: datetime

class ValidationError(Exception):
    """User input fails validation rules (empty, whitespace-only, or exceeds length limits)"""
    def __init__(self, field: str = "", message: str = "") -> None:
        super().__init__(message or field)
        self.field = field
        self.message = message or field

class RecipeProtocol(Protocol):
    def __init__(self) -> None: ...  # declared to take no arguments
    id: UUID
    name: str
    ingredients: str
    created_at: datetime

class RecipeServiceProtocol(Protocol):
    def __init__(self, db: Any) -> None: ...  # db: Session
    def create_recipe(self, name: str, ingredients: str) -> RecipeData: ...
    def update_recipe(self, recipe_id: UUID, name: str, ingredients: str) -> RecipeData: ...
    def get_recipe_by_id(self, recipe_id: UUID) -> Any: ...
    def list_recipes(self) -> list[RecipeData]: ...
