"""The application's database URL — the single source, generated by the scaffold task.

Import this rather than reading the environment yourself:

    from app.db_url import DATABASE_URL

When DATABASE_URL is set it must name the 'psycopg' driver -- the app declares
postgresql and its image ships the distribution providing that module, so a URL asking
for any other DBAPI raises ModuleNotFoundError when the engine is constructed:

    postgresql+psycopg://USER:PASSWORD@HOST:PORT/DATABASE

The deploy injects exactly that. Nothing here hardcodes it: a URL with credentials in
source is a defect on its own.

The fallback is sqlite because it needs no driver and no server, so importing this module
(and therefore the app) succeeds with no database anywhere — which alembic, pytest and the
build-time import check all depend on.
"""
from __future__ import annotations

import os

# The local default: sqlite, which needs no driver and no server.
_SQLITE_DEFAULT = "sqlite:///./app.db"

# The deploy injects DATABASE_URL. Everything else — a developer's laptop, pytest, the
# build-time import check, a static analyser — gets the sqlite default, which always imports.
#
# `or _SQLITE_DEFAULT` rather than just a default argument: an env var set to the EMPTY string
# is present as far as os.environ.get is concerned, so the default never applies and SQLAlchemy
# raises "Could not parse SQLAlchemy URL from given URL string" at import. A blank value means
# unconfigured, and unconfigured means the local default.
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip() or _SQLITE_DEFAULT
