"""Single application entrypoint (generated by the scaffold task).

Composes the plan's component modules by importing their declared seams. Imports
are DEFENSIVE: a missing or incomplete component is logged and skipped, so a
partially built app still starts and can be deployed.

But /health reports the TRUTH about what wired. If every declared seam failed the
app is an empty shell and /health answers 503, so a deployment cannot be declared
healthy on an app that serves nothing."""
from __future__ import annotations

import importlib
import logging

from fastapi import APIRouter, FastAPI
from fastapi.responses import JSONResponse

log = logging.getLogger("app")
app = FastAPI(title="PROJ-0F00E56F-6F73-44E3-9FE2-CED270C1BA81")

# Declared component seams the Technical Lead plan wired into this app.
_SEAMS = [
    'models.database:engine',
    'models.database:SessionLocal',
    'models.recipe:Recipe',
    'services.recipe_service:RecipeService',
    'services.image_service:ImageService',
    'routers.recipes:router',
    # routers.frontend:router is deliberately NOT wired. It is an SPA router whose
    # catch-all GET /{full_path:path} shadows every other route and serves
    # app/web/static/index.html, which this app does not have: the pinned stack is
    # server-rendered (jinja2+htmx) and web.pages:router below owns the pages.
    # With it wired, /health, /login and /recipes all returned 404.
    'integrations.s3_client:S3Client',
    'integrations.db_health:check_db_health',
    'security.sso_middleware:SSOMiddleware',
    'security.authz:verify_ownership',
    'web.pages:router',
]
_WIRED: list[str] = []
_FAILED: dict[str, str] = {}


def _wire() -> None:
    for seam in _SEAMS:
        module_path, _, attr = seam.partition(":")
        try:
            module = importlib.import_module(f"app.{module_path}")
        except Exception as exc:  # component not present/complete yet
            log.warning("seam %s not importable: %s", seam, exc)
            _FAILED[seam] = f"{type(exc).__name__}: {exc}"
            continue
        target = getattr(module, attr, None) if attr else None
        if isinstance(target, APIRouter):
            app.include_router(target)
        _WIRED.append(seam)


_wire()


@app.get("/health")
def health():
    """OK once at least one declared component wired; 503 while none has.

    The failure detail is included so a deploy log says WHICH components are
    missing rather than only that the app is unhealthy."""
    body = {
        "status": "ok" if (_WIRED or not _SEAMS) else "unwired",
        "wired": sorted(_WIRED),
        "failed": _FAILED,
    }
    if _SEAMS and not _WIRED:
        return JSONResponse(body, status_code=503)
    return body
