"""Single application entrypoint (generated by the scaffold task).

Composes the plan's component modules by importing their declared seams.

A component that fails to import is FATAL by default: the app refuses to start and
says which seams failed and why. This is deliberate. Skipping a broken component and
carrying on lets the app answer /health while missing whole layers of itself -- live,
an app wired 7 of 11 seams, served its JSON API perfectly, answered 404 for every page,
and was reported as a successful deployment.

Set SHIFT_ALLOW_PARTIAL_SEAMS=1 to start anyway, for the case the tolerance was written
for: a partially built app during development, where most components do not exist yet.
Then /health still reports the truth in `failed`, and answers 503 if nothing wired."""
from __future__ import annotations

import importlib
import logging
import os

from fastapi import APIRouter, FastAPI
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

log = logging.getLogger("app")
app = FastAPI(title="PROJ-54224B35-9829-4195-B06A-34B7EF170BE3")

# Declared component seams the Technical Lead plan wired into this app.
_SEAMS = [
    'models:Base',
    'models:Recipe',
    'models:get_db',
    'services.recipe_service:RecipeService',
    'web.pages:router',
]
_WIRED: list[str] = []
_FAILED: dict[str, str] = {}


def _wire() -> None:
    for seam in _SEAMS:
        module_path, _, attr = seam.partition(":")
        try:
            module = importlib.import_module(f"app.{module_path}")
        except Exception as exc:  # component not present/complete yet
            log.warning("seam %s not importable: %s", seam, exc)
            _FAILED[seam] = f"{type(exc).__name__}: {exc}"
            continue
        target = getattr(module, attr, None) if attr else None
        if isinstance(target, APIRouter):
            app.include_router(target)
        elif isinstance(target, type) and issubclass(target, BaseHTTPMiddleware):
            # A middleware seam is INSTALLED, not merely imported. Importing it and moving
            # on counted the seam as wired while the middleware never ran: an app that
            # declared a request-filtering middleware deployed green with that filter
            # absent from the request path entirely, because nothing ever added it.
            # Installed here so a declared middleware is actually in force.
            app.add_middleware(target)
        _WIRED.append(seam)


_wire()
if _FAILED and not os.environ.get("SHIFT_ALLOW_PARTIAL_SEAMS"):
    # Refuse to serve a fraction of the app. A container that exits is caught in seconds
    # and its reason is right here; a container that starts half-built looks healthy.
    _detail = "; ".join(f"{seam}: {error}" for seam, error in sorted(_FAILED.items()))
    raise RuntimeError(
        f"refusing to start: {len(_FAILED)} of {len(_SEAMS)} declared components failed to "
        f"import -- {_detail}. Set SHIFT_ALLOW_PARTIAL_SEAMS=1 to start anyway."
    )


@app.get("/health")
def health():
    """OK once at least one declared component wired; 503 while none has.

    The failure detail is included so a deploy log says WHICH components are
    missing rather than only that the app is unhealthy."""
    body = {
        "status": "ok" if (_WIRED or not _SEAMS) else "unwired",
        "wired": sorted(_WIRED),
        "failed": _FAILED,
    }
    if _SEAMS and not _WIRED:
        return JSONResponse(body, status_code=503)
    return body
