"""Tests for the Recipe ORM model and get_db() session factory.

Uses an in-memory SQLite database with foreign keys enabled, mirroring
the production schema's table structure via the shared Base metadata.
"""
import os
import sys
from datetime import datetime

import pytest
from sqlalchemy import create_engine, event
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import sessionmaker

sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
)

from app.models.database import Base, Recipe  # noqa: E402


@pytest.fixture()
def engine():
    eng = create_engine("sqlite:///:memory:", connect_args={"check_same_thread": False})
    event.listen(eng, "connect", lambda c, _: c.execute("PRAGMA foreign_keys=ON"))
    Base.metadata.create_all(eng)
    yield eng
    Base.metadata.drop_all(eng)


@pytest.fixture()
def session_factory(engine):
    return sessionmaker(bind=engine, autocommit=False, autoflush=False, future=True)


def make_get_db(session_factory):
    def get_db():
        db = session_factory()
        try:
            yield db
            db.commit()
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

    return get_db


def test_recipe_instantiates_with_defaults(session_factory):
    db = session_factory()
    recipe = Recipe(name="Pancakes", ingredients="Flour, Eggs, Milk")
    db.add(recipe)
    db.commit()

    assert recipe.id is not None
    assert recipe.name == "Pancakes"
    assert recipe.ingredients == "Flour, Eggs, Milk"
    assert isinstance(recipe.created_at, datetime)
    assert isinstance(recipe.updated_at, datetime)
    db.close()


def test_id_autogenerated_and_immutable(session_factory):
    db = session_factory()
    r1 = Recipe(name="Soup", ingredients="Water, Salt")
    r2 = Recipe(name="Salad", ingredients="Lettuce, Tomato")
    db.add_all([r1, r2])
    db.commit()

    assert r1.id != r2.id
    original_id = r1.id

    r1.name = "Updated Soup"
    db.commit()

    assert r1.id == original_id
    db.close()


def test_unicode_and_length_constraints(session_factory):
    db = session_factory()
    unicode_name = "Crème Brûlée à la Française"
    unicode_ingredients = "Œufs, Crème, Vanille, Sucre"
    recipe = Recipe(name=unicode_name, ingredients=unicode_ingredients)
    db.add(recipe)
    db.commit()

    assert recipe.name == unicode_name
    assert recipe.ingredients == unicode_ingredients

    long_name = "x" * 121
    bad_recipe = Recipe(name=long_name, ingredients="valid")
    db.add(bad_recipe)
    with pytest.raises(Exception):
        db.commit()
    db.rollback()
    db.close()


def test_not_null_constraints_enforced(session_factory):
    db = session_factory()
    recipe = Recipe(name=None, ingredients="Something")
    db.add(recipe)
    with pytest.raises(IntegrityError):
        db.commit()
    db.rollback()
    db.close()


def test_updated_at_refreshed_created_at_unchanged(session_factory):
    db = session_factory()
    recipe = Recipe(name="Stew", ingredients="Beef, Carrots")
    db.add(recipe)
    db.commit()

    original_created_at = recipe.created_at
    original_updated_at = recipe.updated_at

    recipe.ingredients = "Beef, Carrots, Potatoes"
    db.commit()

    assert recipe.created_at == original_created_at
    assert recipe.updated_at >= original_updated_at
    db.close()


def test_get_db_commits_on_success(session_factory):
    get_db = make_get_db(session_factory)
    gen = get_db()
    db = next(gen)
    recipe = Recipe(name="Committed Recipe", ingredients="Test ingredients")
    db.add(recipe)

    try:
        next(gen)
    except StopIteration:
        pass

    verify_db = session_factory()
    found = verify_db.query(Recipe).filter_by(name="Committed Recipe").first()
    assert found is not None
    verify_db.close()


def test_get_db_rolls_back_on_exception(session_factory):
    get_db = make_get_db(session_factory)
    gen = get_db()
    db = next(gen)
    recipe = Recipe(name="Should Rollback", ingredients="Test ingredients")
    db.add(recipe)

    with pytest.raises(RuntimeError):
        gen.throw(RuntimeError("simulated failure"))

    verify_db = session_factory()
    found = verify_db.query(Recipe).filter_by(name="Should Rollback").first()
    assert found is None
    verify_db.close()
